name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Decode and Save SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY_BASE64 }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add EC2 to known hosts
        run: |
          until ssh-keyscan -H ec2-13-48-148-16.eu-north-1.compute.amazonaws.com >> ~/.ssh/known_hosts 2>/dev/null; do
            echo "Waiting for EC2 SSH to be ready..."
            sleep 5
          done

      - name: Connect and Pull Latest Code
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@ec2-13-48-148-16.eu-north-1.compute.amazonaws.com "
            cd githubactionss-demo &&
            git pull origin main &&
            echo '✅ Code pulled successfully on EC2!'
          "
