name: Practice Workflow

on: [push]

jobs:
  practice-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Show uptime
        run: uptime

      - name: Show whoami
        run: whoami

      - name: Run Python script
        run: |
          python3 hello.py
